# Generated by Django 4.1.4 on 2022-12-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src', models.CharField(max_length=255)),
                ('src_id', models.IntegerField()),
                ('src_url', models.URLField()),
                ('src_timestamp', models.DateTimeField()),
                ('is_ai_generated', models.BooleanField()),
            ],
            options={
                'unique_together': {('src', 'src_id')},
            },
        ),
    ]
