# Generated by Django 4.1.4 on 2022-12-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleimage',
            old_name='is_ai_generated',
            new_name='src_is_ai_generated',
        ),
    ]
