"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from decouple import config
from enum import Enum


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'data',
    'web',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / '../data/db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
]


# Program settings (can customize)
MODEL_VER = '20230103-004413'  # ML model used by api
DOWNLOAD_IMAGE_LEN = 200  # Min width and height of images when downloading
IMAGE_LEN = 100  # Width and height of images when training
DATASETS = {  # Datasets used to construct combined dataset
    'laion': {
        'metadata_src': 'url',
        'metadata_type': 'parquet',
        'metadata': [
            'https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus/resolve/main/data/train-00000-of-00007-29aec9150af50f9f.parquet',
            'https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus/resolve/main/data/train-00001-of-00007-060633a36bcf0956.parquet',
            'https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus/resolve/main/data/train-00002-of-00007-709151a2715d894d.parquet',
            'https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus/resolve/main/data/train-00003-of-00007-2dc95366d4278bb8.parquet',
            'https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus/resolve/main/data/train-00004-of-00007-f06fcc8b41bf5fdf.parquet',
            'https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus/resolve/main/data/train-00005-of-00007-f1ec12a5b5b3e6c0.parquet',
            'https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus/resolve/main/data/train-00006-of-00007-57e09e020b9c2df4.parquet',
        ],
        'samples': 10000,
        'is_ai_generated': False,
    },
    'openprompts': {
        'metadata_src': 'gdrive',
        'metadata_type': 'csv',
        'metadata': [
            'https://drive.google.com/uc?id=1c4WHxtlzvHYd0UY5WCMJNn2EO-Aiv2A0',
        ],
        'samples': 10000,
        'is_ai_generated': True,
    },
}

# Program constants (do not need to customize)
DATA_DIR = '../data/'
DATASET_PATH = DATA_DIR + 'dataset.parquet'
TRAIN_SET_PATH = DATA_DIR + 'train-set.csv'
TEST_SET_PATH = DATA_DIR + 'test-set.csv'
MODELS_DIR = DATA_DIR + 'models/'
WEB_IMAGES_DIR = DATA_DIR + 'web_images/'
