FROM nginxproxy/nginx-proxy

# Set environment variables
ENV APP_HOME=/etc/nginx

# Set working directory
WORKDIR $APP_HOME

# Copy files
COPY vhost.d/default vhost.d/default
COPY custom.conf conf.d/custom.conf
