version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/app/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    volumes:
      - postgres_db:/postgres_db
    env_file:
      - ./.env.prod
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - static:/app/static
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  db:
  static:
