version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/app/static
    expose:
      - 8000
    env_file:
      - ./env/.env.prod
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres-db
    image: postgres:16
    volumes:
      - postgres_db:/postgres_db
    env_file:
      - ./env/.env.prod.db
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - static:/app/static
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - app
  acme-companion:
    image: nginxproxy/acme-companion
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ./env/.env.prod.proxy-companion
    depends_on:
      - nginx-proxy

volumes:
  postgres_db:
  static:
  certs:
  html:
  vhost:
  acme:
