version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app:/app
    ports:
      - 8000:8000
    env_file:
      - ./env/.env.dev
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres-db
    image: postgres:16
    volumes:
      - postgres_db:/postgres_db
    env_file:
      - ./env/.env.dev.db

volumes:
  app:
  postgres_db:
