version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    volumes:
      - db:/db
    env_file:
      - ./.env.dev

volumes:
  app:
  db:
