# Pull base image
FROM python:3.11.2-slim

# Set environment variables
ENV APP_HOME=/app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory
WORKDIR $APP_HOME

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends netcat-traditional

# Install Python dependencies
COPY requirements.docker.txt .
RUN pip install --upgrade pip \
    && pip install -r requirements.docker.txt --no-cache-dir

# Copy entrypoint
COPY entrypoint.dev.sh .
RUN sed -i 's/\r$//g' entrypoint.dev.sh \
    && chmod +x entrypoint.dev.sh

# Copy project
COPY . .

# Run entrypoint
ENTRYPOINT ["./entrypoint.dev.sh"]
