pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('src/frontend') {
                    bat 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('src/frontend') {
                    bat 'npm run build-prod'
                }
            }
        }

        stage('Test') {
            steps {
                dir('src/frontend') {
                    bat 'npm run test-prod'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('src/frontend') {
                    withAWS(credentials:'3acc725d-b286-4484-bb14-6d00c6a063af') {
                        s3Upload(file:'dist/frontend', bucket:'s3://ai-art-detector.ricksliu.dev')
                    }                    
                }
            }
        }
    }
}
