# Generated by Django 4.1.4 on 2023-01-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(blank=True, default='', max_length=255)),
                ('model_target', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=5, null=True)),
                ('model_is_ai_generated', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
