# Generated by Django 4.1.4 on 2022-12-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_requestimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestimage',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
