# Generated by Django 4.1.4 on 2022-12-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_requestimage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestimage',
            old_name='is_ai_generated',
            new_name='model_is_ai_generated',
        ),
        migrations.AddField(
            model_name='requestimage',
            name='model_target',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='requestimage',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
