# Generated by Django 4.1.4 on 2022-12-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_is_ai_generated_requestimage_model_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestImage',
            new_name='Image',
        ),
    ]
