# Generated by Django 4.1.4 on 2022-12-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_requestimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='WebImage',
        ),
    ]
